import Head from 'next/head';

function IndexPage() {
  return (
      <Head>
        <title>Nickylink | Portfolio</title>
        <meta
          name="Nickylink Portfolio"
          content="Generated by create next app"
        />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="icon" href="/images/logo1.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
      </Head>
  )
}

export default IndexPage;